apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-external-to-portal-web
  labels:
    app.kubernetes.io/name: geek-hub
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: geek-hub
      app.kubernetes.io/component: portal-web
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 8080
