apiVersion: v1
kind: Secret
metadata:
  name: geek-hub-secret
  labels:
    app.kubernetes.io/name: geek-hub
    app.kubernetes.io/component: shared-config
type: Opaque
stringData:
  REDIS_PASSWORD: "change-me-redis-password"
  MONGODB_USERNAME: "geekhub-app"
  MONGODB_PASSWORD: "ghubLoginWriterA7s3N5xQ2pL8"
