apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: match-core
  labels:
    app.kubernetes.io/name: geek-hub
    app.kubernetes.io/component: match-core
    release: observability-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: geek-hub
      app.kubernetes.io/component: match-core
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
