apiVersion: v1
kind: Service
metadata:
  name: match-core
  labels:
    app.kubernetes.io/name: geek-hub
    app.kubernetes.io/component: match-core
spec:
  selector:
    app.kubernetes.io/name: geek-hub
    app.kubernetes.io/component: match-core
  ports:
    - name: grpc
      port: 50052
      targetPort: grpc
    - name: metrics
      port: 9090
      targetPort: metrics
