apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-platform-http
  labels:
    app.kubernetes.io/name: geek-hub
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values:
          - portal-web
          - games-web
          - realtime-gateway
          - login-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
        - podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: realtime-gateway-egress
  labels:
    app.kubernetes.io/name: geek-hub
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: geek-hub
      app.kubernetes.io/component: realtime-gateway
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: geek-hub
              app.kubernetes.io/component: match-core
      ports:
        - protocol: TCP
          port: 50052
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchExpressions:
              - key: k8s-app
                operator: In
                values:
                  - kube-dns
                  - coredns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: login-service-egress
  labels:
    app.kubernetes.io/name: geek-hub
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: geek-hub
      app.kubernetes.io/component: login-service
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: mongodb
          podSelector:
            matchLabels:
              app.kubernetes.io/component: mongodb
              app.kubernetes.io/instance: mongodb
              app.kubernetes.io/name: mongodb
      ports:
        - protocol: TCP
          port: 27017
    - to:
        - ipBlock:
            cidr: 192.168.0.100/32
      ports:
        - protocol: TCP
          port: 32017
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchExpressions:
              - key: k8s-app
                operator: In
                values:
                  - kube-dns
                  - coredns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: match-core-egress
  labels:
    app.kubernetes.io/name: geek-hub
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: geek-hub
      app.kubernetes.io/component: match-core
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: geek-hub
              app.kubernetes.io/component: redis
      ports:
        - protocol: TCP
          port: 6379
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: geek-hub
              app.kubernetes.io/component: bot-engine
      ports:
        - protocol: TCP
          port: 50051
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchExpressions:
              - key: k8s-app
                operator: In
                values:
                  - kube-dns
                  - coredns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-match-core-to-redis
  labels:
    app.kubernetes.io/name: geek-hub
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: geek-hub
      app.kubernetes.io/component: redis
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: geek-hub
              app.kubernetes.io/component: match-core
      ports:
        - protocol: TCP
          port: 6379
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-match-core-to-bot-engine
  labels:
    app.kubernetes.io/name: geek-hub
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: geek-hub
      app.kubernetes.io/component: bot-engine
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: geek-hub
              app.kubernetes.io/component: match-core
      ports:
        - protocol: TCP
          port: 50051
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-realtime-gateway-to-match-core
  labels:
    app.kubernetes.io/name: geek-hub
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: geek-hub
      app.kubernetes.io/component: match-core
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: geek-hub
              app.kubernetes.io/component: realtime-gateway
      ports:
        - protocol: TCP
          port: 50052
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-monitoring-to-realtime-gateway-metrics
  labels:
    app.kubernetes.io/name: geek-hub
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: geek-hub
      app.kubernetes.io/component: realtime-gateway
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 3000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-monitoring-to-login-service-metrics
  labels:
    app.kubernetes.io/name: geek-hub
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: geek-hub
      app.kubernetes.io/component: login-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 3000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-monitoring-to-match-core-metrics
  labels:
    app.kubernetes.io/name: geek-hub
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: geek-hub
      app.kubernetes.io/component: match-core
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 9090
