apiVersion: v1
kind: Service
metadata:
  name: realtime-gateway
  labels:
    app.kubernetes.io/name: geek-hub
    app.kubernetes.io/component: realtime-gateway
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: geek-hub
    app.kubernetes.io/component: realtime-gateway
  ports:
    - name: http
      port: 3000
      targetPort: http
