apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  labels:
    app.kubernetes.io/name: geek-hub
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
